services:
  test-before:
    build: .
    command: node --expose-gc dist/tests/test.js --repo=../repository_before/safaricom_calls
  test-after:
    build: .
    command: node --expose-gc dist/tests/test.js --repo=../repository_after/safaricom_calls
  evaluation:
    build: .
    command: node --expose-gc dist/evaluation/evaluation.js
    volumes:
      - ./evaluation:/app/evaluation