services:
  backend:
    image: hailu3548/document-app-backend:latest
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py seed_demo && python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: hailu3548/document-app-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
