services:
  app:
    build: .
    command: go test -v .
    volumes:
      - .:/app
    working_dir: /app/repository_after

  test-after:
    build:
      context: .
      target: builder
    command: go test -v .
    volumes:
      - .:/app
    working_dir: /app/tests

  evaluate:
    build:
      context: .
      target: builder
    command: go run evaluation/evaluation.go
    volumes:
      - .:/app
    working_dir: /app
