services:
  app:
    build: .
    volumes:
      - .:/app # Mount project folder
    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
    environment:
      - PATH=/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
