services:
  test:
    build: .
    image: dependency-resolver:latest
    command: pytest -v tests
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app

  evaluation:
    image: dependency-resolver:latest
    command: python evaluation/evaluation.py
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
