services:
  test:
    build: .
    working_dir: /app/tests
    environment:
      - CI=true
    command: npm test
    
  evaluation:
    build: .
    working_dir: /app
    command: ["sh", "-c", "sleep 3 && node evaluation/evaluation.js"]
    volumes:
      - .:/host:rw

