services:
  evaluation:
    build: .
    working_dir: /app
    command: ["sh", "-c", "sleep 3 && node evaluation/evaluation.js"]
    volumes:
      - .:/host:rw
  live:
    build: .
    working_dir: /app/repository_after
    command: npm start
    ports:
      - "3000:3000"

  test:
    build: .
    working_dir: /app/repository_after
    environment:
      - CI=true
    command: npm test

