
services:
  before:
    build: .
    environment:
      - TARGET=BEFORE
    command: pytest -v tests/test_overall.py
    volumes:
      - .:/app

  after:
    build: .
    environment:
      - TARGET=AFTER
    command: pytest -v tests/test_overall.py
    volumes:
      - .:/app

  evaluate:
    build: .
    command: python evaluation/evaluation.py
    volumes:
      - .:/app
