services:
  repository_before-test:
    build: .
    container_name: before-test
    command: python tests/run_single_repo_test.py repository_before
    volumes:
      - .:/app
    working_dir: /app

  repository_after-test:
    build: .
    container_name: after-test
    command: python tests/run_single_repo_test.py repository_after
    volumes:
      - .:/app
    working_dir: /app

  evaluation:
    build: .
    container_name: evaluation
    command: python evaluation/evaluation.py
    volumes:
      - .:/app
    working_dir: /app
