services:
  evaluation:
    build: .
    working_dir: /app
    command: ["sh", "-c", "sleep 3 && node evaluation/evaluation.js"]
    environment:
      - CI=true
    volumes:
      - .:/host:rw
  test:
    build: .
    working_dir: /app
    command: ["npm", "test"]
    environment:
      - CI=true