services:
  test:
    build: .
    working_dir: /app
    command: ["npm", "test"]
    volumes:
      - .:/host:rw
  evaluation:
    build: .
    working_dir: /app
    command: ["node", "evaluation/evaluation.js"]