services:
  test-after:
    build: .
    command: sh -c "cd tests && go mod tidy && go test -v -race ./..."
    volumes:
      - .:/app
    working_dir: /app

  evaluation:
    build: .
    command: sh -c "cd evaluation && go mod tidy && go run Evaluation.go"
    volumes:
      - .:/app
    working_dir: /app