services:
  app-before:
    build: .
    volumes:
      - .:/app
    environment:
      - REPO_PATH=repository_before
      - RUN_EVALUATION=${RUN_EVALUATION:-false}

  app-after:
    build: .
    volumes:
      - .:/app
    environment:
      - REPO_PATH=repository_after
      - RUN_EVALUATION=${RUN_EVALUATION:-false}
