services:
  app:
    build: .
    command: sh -c "npm install --no-audit --no-fund --quiet --no-update-notifier --silent && npm test --silent"
    volumes:
      - .:/app
      - /app/node_modules

  evaluate:
    build: .
    command: sh -c "npm install --no-audit --no-fund --quiet --no-update-notifier --silent && npm run evaluate --silent"
    volumes:
      - .:/app
      - /app/node_modules
