services:
  test-before:
    build: .
    profiles: ["test-before"]
    command: sh -c "PYTHONPATH=/app/repository_before python -m pytest -v tests || true"
    volumes:
      - .:/app

  test-after:
    build: .
    profiles: ["test-after"]
    command: sh -c "PYTHONPATH=/app/repository_after python -m pytest -v tests"
    volumes:
      - .:/app

  evaluate:
    build: .
    profiles: ["evaluation"]
    command: python evaluation/evaluation.py
    volumes:
      - .:/app
