services:
  test-after:
    build: .
    working_dir: /app/repository_after
    command: sh -c "npm install && npm test"
    volumes:
      - .:/app

  evaluation:
    build: .
    working_dir: /app
    command: node evaluation/evaluation.js
    volumes:
      - .:/app
